# Generated by Django 5.2.5 on 2025-08-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='from_where',
            field=models.CharField(choices=[('movie', 'Фильм'), ('book', 'Книга')], max_length=140),
        ),
    ]
