# Generated by Django 5.2.5 on 2025-08-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_quote', '0002_alter_source_from_where'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='from_where',
            field=models.CharField(choices=[('movie', 'Фильм'), ('book', 'Книга')], default='book', max_length=140),
        ),
    ]
